# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'InCheck' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InCheck
  pod ‘Realm’, git:'https://github.com/realm/realm-cocoa.git', 
   	branch: 'master’,:submodules => true
  pod 'RealmSwift', git: 'https://github.com/realm/realm-cocoa.git', 
  	branch: 'master’,:submodules => true

end
